export const AZURE_OPENAI_API_KEY = process.env.AZURE_OPENAI_API_KEY;
export const AZURE_OPENAI_API_VERSION = process.env.AZURE_OPENAI_API_VERSION;
export const AZURE_OPENAI_API_RESOURCE = process.env.AZURE_OPENAI_API_RESOURCE;
export const AZURE_OPENAI_API_DEPLOYMENT = process.env.AZURE_OPENAI_API_DEPLOYMENT || '';
