export let AZURE_OPENAI_API_KEY = '';
export let AZURE_OPENAI_API_VERSION = '';
export let AZURE_OPENAI_API_ENDPOINT = '';
export let AZURE_OPENAI_API_DEPLOYMENT = '';

if (process.env.AZURE_OPENAI_API === 'true') {
  AZURE_OPENAI_API_KEY = process.env.AZURE_OPENAI_API_KEY ?? '';
  AZURE_OPENAI_API_VERSION = process.env.AZURE_OPENAI_API_VERSION ?? '';
  AZURE_OPENAI_API_ENDPOINT = process.env.AZURE_OPENAI_API_ENDPOINT ?? '';
  AZURE_OPENAI_API_DEPLOYMENT = process.env.AZURE_OPENAI_API_DEPLOYMENT ?? '';
}
